name: english_words_quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  # uuid 패키지가 빠져있어서 추가했습니다. 나만의 단어장 기능에 필요합니다.
  uuid: ^4.3.3
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # 버전이 달라서 최신 버전으로 수정했습니다.
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/english_words/
    - assets/icon/
    - assets/hangman_images/

# --- 여기서부터가 중요합니다 ---
# flutter: 섹션 밖으로 나와서, 맨 왼쪽부터 시작해야 합니다.

# 1. 스플래시 스크린 설정
flutter_native_splash:
  color: "#EDE7F6" # 배경색 (연한 보라색)
  image: assets/icon/icon.png # 중앙에 표시될 로고 이미지

  # Android 12 이상을 위한 설정
  android_12:
    color: "#EDE7F6"
    image: assets/icon/icon.png

# 2. 앱 아이콘 설정
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # Android 최소 지원 버전