// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSDdhlKFlNCIjrseSq5r5894lMpc-RpQ',
    appId: '1:788518785608:web:2a03c45cba6d73ce017e7d',
    messagingSenderId: '788518785608',
    projectId: 'english-words-quiz-app-5db5a',
    authDomain: 'english-words-quiz-app-5db5a.firebaseapp.com',
    storageBucket: 'english-words-quiz-app-5db5a.firebasestorage.app',
    measurementId: 'G-WHC7SXJE69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN5a6LdWzemFRe8Bkm-Vt0lXHYIieLl0M',
    appId: '1:788518785608:android:e23e90225184e7bf017e7d',
    messagingSenderId: '788518785608',
    projectId: 'english-words-quiz-app-5db5a',
    storageBucket: 'english-words-quiz-app-5db5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Df790_mg2RKROgiPmVVEJ0tu3jXsh7M',
    appId: '1:788518785608:ios:79e8d0103f3c49d5017e7d',
    messagingSenderId: '788518785608',
    projectId: 'english-words-quiz-app-5db5a',
    storageBucket: 'english-words-quiz-app-5db5a.firebasestorage.app',
    iosBundleId: 'com.example.englishWordsQuizApp',
  );
}
